-- =====================================================================
-- Tulip+ tenant-service — V1 초기 스키마 (Sprint 1-C)
-- ---------------------------------------------------------------------
-- 작성자 : DBA Agent
-- 작성일 : 2026-05-11
-- 변경요약: tnt_tenant / tnt_library / tnt_library_branch / tnt_tenant_setting
--           + tnt_outbox + RLS 정책 + updated_at 트리거 + audit 트리거
-- 참조   : 10_dba/01_data_modeling_principles.md (§2 RLS, §6 공통컬럼)
--          10_dba/06_security_and_access_control.md (§2 Role)
--          04_dev_lead/05_security_and_auth.md (§4 테넌트 컨텍스트)
--          04_dev_lead/07_phase1_sprint_plan.md (§5 Sprint 1-C)
-- 호환   : V1__init_common.sql (tlp_cmn_tenant 와는 별도 도메인 스키마)
--          본 서비스는 자체 스키마(tenant-service DB)로 운영되며,
--          tnt_* 테이블은 Phase 1-C의 정식 도메인 모델로 사용한다.
-- =====================================================================

-- ----- 확장 활성화 (멱등) -----
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

-- ----- 공통: updated_at / version 자동 트리거 (중복 정의 무해) -----
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    NEW.version   := COALESCE(OLD.version, 0) + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----- 공통: 현재 테넌트 컨텍스트 헬퍼 -----
CREATE OR REPLACE FUNCTION fn_current_tenant_id()
RETURNS BIGINT AS $$
BEGIN
    RETURN NULLIF(current_setting('app.current_tenant', true), '')::BIGINT;
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE OR REPLACE FUNCTION fn_current_app_role()
RETURNS TEXT AS $$
BEGIN
    RETURN NULLIF(current_setting('app.role', true), '');
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql STABLE;

-- =====================================================================
-- 1. tnt_tenant — 테넌트 마스터
--    플랫폼 격리 최상위. 일반 사용자(app_user)는 본 테이블을 조회할 수
--    없으며, SYS_ADMIN 만 SELECT/INSERT/UPDATE/DELETE 가능 (RLS 명시).
-- =====================================================================
CREATE TABLE tnt_tenant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       VARCHAR(26)  NOT NULL,                      -- ULID, 외부 노출 식별자
    code            VARCHAR(64)  NOT NULL,                      -- 테넌트 코드 (URL slug)
    name            VARCHAR(255) NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
                       CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED')),
    plan            VARCHAR(32)  NOT NULL DEFAULT 'STANDARD',   -- STANDARD/PROFESSIONAL/ENTERPRISE
    primary_locale  VARCHAR(10)  NOT NULL DEFAULT 'ko-KR',
    primary_timezone VARCHAR(40) NOT NULL DEFAULT 'Asia/Seoul',
    contact_json    JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    deleted_at      TIMESTAMPTZ,
    version         INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_tnt_tenant_public_id UNIQUE (public_id)
);

COMMENT ON TABLE  tnt_tenant            IS '테넌트(고객 도서관 조직). SYS_ADMIN 만 접근.';
COMMENT ON COLUMN tnt_tenant.public_id  IS '외부 노출용 ULID 식별자';
COMMENT ON COLUMN tnt_tenant.code       IS '테넌트 코드 (URL slug, 대소문자 무시 유일)';
COMMENT ON COLUMN tnt_tenant.status     IS 'ACTIVE=활성, SUSPENDED=일시정지, CLOSED=종료';
COMMENT ON COLUMN tnt_tenant.plan       IS '구독 플랜 코드';

-- 코드 유일성: soft-delete 미고려, 대소문자 무시
CREATE UNIQUE INDEX uk_tnt_tenant_code_active
    ON tnt_tenant (LOWER(code))
    WHERE deleted_at IS NULL;

CREATE INDEX ix_tnt_tenant_status
    ON tnt_tenant (status)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_tnt_tenant_bu
    BEFORE UPDATE ON tnt_tenant
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 2. tnt_library — 도서관(중앙/분관/통합)
--    한 테넌트가 다수의 라이브러리를 운영 가능.
--    type=CENTRAL(중앙) / BRANCH(분관) / INTEGRATED(통합) — 비즈니스 분류.
-- =====================================================================
CREATE TABLE tnt_library (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         VARCHAR(26)  NOT NULL,
    tenant_id         BIGINT       NOT NULL REFERENCES tnt_tenant(id)
                          ON DELETE RESTRICT,
    code              VARCHAR(64)  NOT NULL,
    name              VARCHAR(255) NOT NULL,
    type              VARCHAR(16)  NOT NULL DEFAULT 'CENTRAL'
                          CHECK (type IN ('CENTRAL','BRANCH','INTEGRATED')),
    status            VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
                          CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED')),
    address_json      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    contact_json      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    opening_hours_json JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by        BIGINT,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by        BIGINT,
    deleted_at        TIMESTAMPTZ,
    version           INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_tnt_library_public_id UNIQUE (public_id)
);

COMMENT ON TABLE  tnt_library              IS '테넌트 내 라이브러리(중앙관/분관/통합). RLS 격리.';
COMMENT ON COLUMN tnt_library.type         IS 'CENTRAL=중앙, BRANCH=분관, INTEGRATED=통합';
COMMENT ON COLUMN tnt_library.address_json IS '주소 (zipcode/addr1/addr2/lat/lng 등)';

CREATE UNIQUE INDEX uk_tnt_library_tenant_code
    ON tnt_library (tenant_id, LOWER(code))
    WHERE deleted_at IS NULL;

CREATE INDEX ix_tnt_library_tenant       ON tnt_library (tenant_id);
CREATE INDEX ix_tnt_library_tenant_status ON tnt_library (tenant_id, status)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_tnt_library_bu
    BEFORE UPDATE ON tnt_library
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 3. tnt_library_branch — 분관 (라이브러리 하위 운영 단위)
--    다관 통합 운영 시 라이브러리 아래에 다수 분관 존재.
--    소장(holding)·등록번호 채번은 분관 단위로 운영 (DBA §11 참고).
-- =====================================================================
CREATE TABLE tnt_library_branch (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     VARCHAR(26)  NOT NULL,
    tenant_id     BIGINT       NOT NULL REFERENCES tnt_tenant(id)
                      ON DELETE RESTRICT,
    library_id    BIGINT       NOT NULL REFERENCES tnt_library(id)
                      ON DELETE RESTRICT,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(255) NOT NULL,
    status        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
                      CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED')),
    address_json  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    contact_json  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by    BIGINT,
    deleted_at    TIMESTAMPTZ,
    version       INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_tnt_library_branch_public_id UNIQUE (public_id)
);

COMMENT ON TABLE tnt_library_branch IS '라이브러리 하위 분관(소장/채번 단위). tenant_id 중복 보유는 RLS 단순화 목적.';

CREATE UNIQUE INDEX uk_tnt_library_branch_lib_code
    ON tnt_library_branch (library_id, LOWER(code))
    WHERE deleted_at IS NULL;

CREATE INDEX ix_tnt_library_branch_tenant      ON tnt_library_branch (tenant_id);
CREATE INDEX ix_tnt_library_branch_library     ON tnt_library_branch (library_id);
CREATE INDEX ix_tnt_library_branch_tenant_lib  ON tnt_library_branch (tenant_id, library_id, status)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_tnt_library_branch_bu
    BEFORE UPDATE ON tnt_library_branch
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 4. tnt_tenant_setting — 테넌트 환경설정 KV
--    key = 'NAMESPACE.KEY' (예: 'CIRCULATION.MAX_LOAN_DAYS')
-- =====================================================================
CREATE TABLE tnt_tenant_setting (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL REFERENCES tnt_tenant(id) ON DELETE CASCADE,
    key         VARCHAR(128) NOT NULL,
    value_json  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    deleted_at  TIMESTAMPTZ,
    version     INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_tnt_tenant_setting_key UNIQUE (tenant_id, key)
);

COMMENT ON TABLE  tnt_tenant_setting        IS '테넌트별 환경설정 KV 저장소';
COMMENT ON COLUMN tnt_tenant_setting.key    IS 'NAMESPACE.KEY 형식 (대문자, 점 구분)';

CREATE INDEX ix_tnt_tenant_setting_tenant ON tnt_tenant_setting (tenant_id);

CREATE TRIGGER trg_tnt_tenant_setting_bu
    BEFORE UPDATE ON tnt_tenant_setting
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 5. tnt_outbox — 도메인 이벤트 Outbox (Sprint 1-C.7)
--    Polling Publisher 가 status=PENDING 행을 Kafka 발행 후 COMPLETED 갱신.
-- =====================================================================
CREATE TABLE tnt_outbox (
    id              BIGSERIAL PRIMARY KEY,
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(128) NOT NULL,
    payload         JSONB        NOT NULL,
    tenant_id       BIGINT,
    occurred_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed_at    TIMESTAMPTZ,
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING'
                       CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED')),
    last_error      TEXT,
    trace_id        VARCHAR(64)
);

COMMENT ON TABLE tnt_outbox IS '테넌트 도메인 이벤트 Outbox (Polling Publisher 대상)';

-- 폴링 패턴 인덱스: PENDING 만 occurred_at 오름차순 스캔
CREATE INDEX ix_tnt_outbox_status_occurred
    ON tnt_outbox (status, occurred_at)
    WHERE status IN ('PENDING','PROCESSING');

CREATE INDEX ix_tnt_outbox_tenant_occurred
    ON tnt_outbox (tenant_id, occurred_at DESC);

-- =====================================================================
-- 6. RLS 활성화 및 정책 (SELECT/INSERT/UPDATE/DELETE 4종 명시)
--    BYPASSRLS 는 마이그레이션·운영 admin(tulip_super, tulip_dba) 만.
-- =====================================================================

-- 6.1 tnt_tenant : SYS_ADMIN 만 접근 가능
ALTER TABLE tnt_tenant ENABLE ROW LEVEL SECURITY;
ALTER TABLE tnt_tenant FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_tnt_tenant_sys_select ON tnt_tenant;
CREATE POLICY pol_tnt_tenant_sys_select ON tnt_tenant
    FOR SELECT
    USING (fn_current_app_role() = 'SYS_ADMIN');

DROP POLICY IF EXISTS pol_tnt_tenant_sys_insert ON tnt_tenant;
CREATE POLICY pol_tnt_tenant_sys_insert ON tnt_tenant
    FOR INSERT
    WITH CHECK (fn_current_app_role() = 'SYS_ADMIN');

DROP POLICY IF EXISTS pol_tnt_tenant_sys_update ON tnt_tenant;
CREATE POLICY pol_tnt_tenant_sys_update ON tnt_tenant
    FOR UPDATE
    USING (fn_current_app_role() = 'SYS_ADMIN')
    WITH CHECK (fn_current_app_role() = 'SYS_ADMIN');

DROP POLICY IF EXISTS pol_tnt_tenant_sys_delete ON tnt_tenant;
CREATE POLICY pol_tnt_tenant_sys_delete ON tnt_tenant
    FOR DELETE
    USING (fn_current_app_role() = 'SYS_ADMIN');

-- 6.2 tnt_library : tenant_id 매칭
ALTER TABLE tnt_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE tnt_library FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_tnt_library_sel ON tnt_library;
CREATE POLICY pol_tnt_library_sel ON tnt_library
    FOR SELECT USING (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_tnt_library_ins ON tnt_library;
CREATE POLICY pol_tnt_library_ins ON tnt_library
    FOR INSERT WITH CHECK (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_tnt_library_upd ON tnt_library;
CREATE POLICY pol_tnt_library_upd ON tnt_library
    FOR UPDATE
    USING (tenant_id = fn_current_tenant_id())
    WITH CHECK (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_tnt_library_del ON tnt_library;
CREATE POLICY pol_tnt_library_del ON tnt_library
    FOR DELETE USING (tenant_id = fn_current_tenant_id());

-- 6.3 tnt_library_branch : tenant_id 매칭
ALTER TABLE tnt_library_branch ENABLE ROW LEVEL SECURITY;
ALTER TABLE tnt_library_branch FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_tnt_library_branch_sel ON tnt_library_branch;
CREATE POLICY pol_tnt_library_branch_sel ON tnt_library_branch
    FOR SELECT USING (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_tnt_library_branch_ins ON tnt_library_branch;
CREATE POLICY pol_tnt_library_branch_ins ON tnt_library_branch
    FOR INSERT WITH CHECK (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_tnt_library_branch_upd ON tnt_library_branch;
CREATE POLICY pol_tnt_library_branch_upd ON tnt_library_branch
    FOR UPDATE
    USING (tenant_id = fn_current_tenant_id())
    WITH CHECK (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_tnt_library_branch_del ON tnt_library_branch;
CREATE POLICY pol_tnt_library_branch_del ON tnt_library_branch
    FOR DELETE USING (tenant_id = fn_current_tenant_id());

-- 6.4 tnt_tenant_setting : tenant_id 매칭
ALTER TABLE tnt_tenant_setting ENABLE ROW LEVEL SECURITY;
ALTER TABLE tnt_tenant_setting FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_tnt_tenant_setting_sel ON tnt_tenant_setting;
CREATE POLICY pol_tnt_tenant_setting_sel ON tnt_tenant_setting
    FOR SELECT USING (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_tnt_tenant_setting_ins ON tnt_tenant_setting;
CREATE POLICY pol_tnt_tenant_setting_ins ON tnt_tenant_setting
    FOR INSERT WITH CHECK (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_tnt_tenant_setting_upd ON tnt_tenant_setting;
CREATE POLICY pol_tnt_tenant_setting_upd ON tnt_tenant_setting
    FOR UPDATE
    USING (tenant_id = fn_current_tenant_id())
    WITH CHECK (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_tnt_tenant_setting_del ON tnt_tenant_setting;
CREATE POLICY pol_tnt_tenant_setting_del ON tnt_tenant_setting
    FOR DELETE USING (tenant_id = fn_current_tenant_id());

-- 6.5 tnt_outbox : tenant_id 일치 또는 시스템 이벤트(tenant_id NULL) 허용
ALTER TABLE tnt_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE tnt_outbox FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_tnt_outbox_sel ON tnt_outbox;
CREATE POLICY pol_tnt_outbox_sel ON tnt_outbox
    FOR SELECT
    USING (
        tenant_id = fn_current_tenant_id()
        OR (tenant_id IS NULL AND fn_current_app_role() = 'SYS_ADMIN')
    );

DROP POLICY IF EXISTS pol_tnt_outbox_ins ON tnt_outbox;
CREATE POLICY pol_tnt_outbox_ins ON tnt_outbox
    FOR INSERT
    WITH CHECK (
        tenant_id = fn_current_tenant_id()
        OR (tenant_id IS NULL AND fn_current_app_role() = 'SYS_ADMIN')
    );

DROP POLICY IF EXISTS pol_tnt_outbox_upd ON tnt_outbox;
CREATE POLICY pol_tnt_outbox_upd ON tnt_outbox
    FOR UPDATE
    USING (
        tenant_id = fn_current_tenant_id()
        OR (tenant_id IS NULL AND fn_current_app_role() = 'SYS_ADMIN')
    )
    WITH CHECK (
        tenant_id = fn_current_tenant_id()
        OR (tenant_id IS NULL AND fn_current_app_role() = 'SYS_ADMIN')
    );

DROP POLICY IF EXISTS pol_tnt_outbox_del ON tnt_outbox;
CREATE POLICY pol_tnt_outbox_del ON tnt_outbox
    FOR DELETE
    USING (fn_current_app_role() = 'SYS_ADMIN');

-- =====================================================================
-- 7. 감사 로그 트리거 (간이) — 본 마이그레이션에서는 트리거 후크만 정의.
--    실제 적재는 BackendSenior 의 common-data/audit 라이브러리가 담당.
--    여기서는 tnt_tenant/tnt_library/tnt_library_branch 변경 후 NOTIFY.
-- =====================================================================
CREATE OR REPLACE FUNCTION fn_tnt_audit_notify()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM pg_notify(
        'tnt_audit',
        json_build_object(
            'table', TG_TABLE_NAME,
            'op',    TG_OP,
            'id',    COALESCE(NEW.id, OLD.id),
            'at',    now()
        )::text
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tnt_tenant_aiud
    AFTER INSERT OR UPDATE OR DELETE ON tnt_tenant
    FOR EACH ROW EXECUTE FUNCTION fn_tnt_audit_notify();

CREATE TRIGGER trg_tnt_library_aiud
    AFTER INSERT OR UPDATE OR DELETE ON tnt_library
    FOR EACH ROW EXECUTE FUNCTION fn_tnt_audit_notify();

CREATE TRIGGER trg_tnt_library_branch_aiud
    AFTER INSERT OR UPDATE OR DELETE ON tnt_library_branch
    FOR EACH ROW EXECUTE FUNCTION fn_tnt_audit_notify();

-- =====================================================================
-- 8. 개발 환경 시드 (Sprint 1-C 데모: demo-1, demo-2)
--    운영 배포 시에는 별도 데이터 마이그레이션 사용. (멱등 처리)
-- =====================================================================
INSERT INTO tnt_tenant (id, public_id, code, name, status, plan)
VALUES
    (1, '01HEMOTENANT00000000000001', 'demo-1', '데모 도서관 1', 'ACTIVE', 'STANDARD'),
    (2, '01HEMOTENANT00000000000002', 'demo-2', '데모 도서관 2', 'ACTIVE', 'STANDARD')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tnt_library (id, public_id, tenant_id, code, name, type, status)
VALUES
    (1, '01HEMOLIBRARY0000000000001', 1, 'main',   '데모1 중앙관', 'CENTRAL', 'ACTIVE'),
    (2, '01HEMOLIBRARY0000000000002', 2, 'main',   '데모2 중앙관', 'CENTRAL', 'ACTIVE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tnt_library_branch (id, public_id, tenant_id, library_id, code, name, status)
VALUES
    (1, '01HEMOBRANCH00000000000001', 1, 1, 'main',  '데모1 본관', 'ACTIVE'),
    (2, '01HEMOBRANCH00000000000002', 2, 1, 'main',  '데모2 본관', 'ACTIVE')
ON CONFLICT (id) DO NOTHING;

-- IDENTITY 시퀀스 동기화
SELECT setval(pg_get_serial_sequence('tnt_tenant','id'),
              (SELECT GREATEST(MAX(id), 1) FROM tnt_tenant));
SELECT setval(pg_get_serial_sequence('tnt_library','id'),
              (SELECT GREATEST(MAX(id), 1) FROM tnt_library));
SELECT setval(pg_get_serial_sequence('tnt_library_branch','id'),
              (SELECT GREATEST(MAX(id), 1) FROM tnt_library_branch));

-- =====================================================================
-- 끝.
-- =====================================================================
