-- =====================================================================
-- Tulip+ member-service — V1 초기 스키마 (Sprint 1-C)
-- ---------------------------------------------------------------------
-- 작성자 : DBA Agent
-- 작성일 : 2026-05-11
-- 변경요약: mbr_member / mbr_member_address / mbr_member_card /
--           mbr_member_consent / mbr_member_credential / mbr_member_role
--           + mbr_outbox + RLS(tenant_id 격리) + pgcrypto PII 암호화
--           + trgm 인덱스(이름·전화·이메일 검색)
-- 참조   : 10_dba/01_data_modeling_principles.md (§6 공통컬럼, §12 PII)
--          10_dba/06_security_and_access_control.md (§2 Role, §3 RLS)
--          04_dev_lead/05_security_and_auth.md (§4 테넌트 컨텍스트)
--          04_dev_lead/07_phase1_sprint_plan.md (§5 Sprint 1-C.2, 1-C.12)
-- 주의   : pgcrypto 키는 'app.kms_key' 세션 변수로 주입.
--          데모용 placeholder 값은 application.yml 의 DataSourceInitializer 가
--          SET app.kms_key = '<demo-only>' 로 설정한다. 운영에서는 KMS 연동.
-- =====================================================================

-- ----- 확장 -----
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS btree_gin;

-- ----- 공통 트리거/헬퍼 (중복 정의 무해) -----
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    NEW.version   := COALESCE(OLD.version, 0) + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_current_tenant_id()
RETURNS BIGINT AS $$
BEGIN
    RETURN NULLIF(current_setting('app.current_tenant', true), '')::BIGINT;
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql STABLE;

-- ----- PII 암호화 헬퍼 -----
-- 세션 변수 app.kms_key 에 들어있는 대칭키로 pgp_sym_encrypt.
-- 변수 미설정 시 예외 발생(insert 자체가 실패하도록).
CREATE OR REPLACE FUNCTION fn_encrypt_pii(p_plain TEXT)
RETURNS BYTEA AS $$
DECLARE
    v_key TEXT;
BEGIN
    IF p_plain IS NULL THEN
        RETURN NULL;
    END IF;
    v_key := current_setting('app.kms_key', true);
    IF v_key IS NULL OR v_key = '' THEN
        RAISE EXCEPTION 'app.kms_key 세션 변수가 설정되지 않았습니다.';
    END IF;
    RETURN pgp_sym_encrypt(p_plain, v_key, 'cipher-algo=aes256');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_decrypt_pii(p_cipher BYTEA)
RETURNS TEXT AS $$
DECLARE
    v_key TEXT;
BEGIN
    IF p_cipher IS NULL THEN
        RETURN NULL;
    END IF;
    v_key := current_setting('app.kms_key', true);
    IF v_key IS NULL OR v_key = '' THEN
        RAISE EXCEPTION 'app.kms_key 세션 변수가 설정되지 않았습니다.';
    END IF;
    RETURN pgp_sym_decrypt(p_cipher, v_key);
END;
$$ LANGUAGE plpgsql;

-- 정규화 헬퍼 (검색 보조용 — 소문자 + 다이아크리틱 제거 + 공백 단일화)
CREATE OR REPLACE FUNCTION fn_normalize_name(p_text TEXT)
RETURNS TEXT AS $$
    SELECT lower(regexp_replace(unaccent(coalesce(p_text, '')), '\s+', ' ', 'g'))
$$ LANGUAGE sql IMMUTABLE;

-- 전화번호 정규화 (숫자만 남김)
CREATE OR REPLACE FUNCTION fn_normalize_phone(p_text TEXT)
RETURNS TEXT AS $$
    SELECT regexp_replace(coalesce(p_text, ''), '\D', '', 'g')
$$ LANGUAGE sql IMMUTABLE;

-- =====================================================================
-- 1. mbr_member — 회원 마스터
--    PII: phone(암호화) / address(별도 테이블) / 이메일(평문+lower 해시)
--    검색: name_normalized / phone_normalized / email_lower 에 GIN(trgm)
-- =====================================================================
CREATE TABLE mbr_member (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           VARCHAR(26)  NOT NULL,
    tenant_id           BIGINT       NOT NULL,
    library_id          BIGINT       NOT NULL DEFAULT 0,
    member_no           VARCHAR(32)  NOT NULL,            -- 테넌트 내 회원번호
    name                VARCHAR(120) NOT NULL,
    name_normalized     VARCHAR(200) GENERATED ALWAYS AS (fn_normalize_name(name)) STORED,
    birthdate           DATE,
    gender              VARCHAR(8) CHECK (gender IN ('M','F','N','U') OR gender IS NULL),
    email               VARCHAR(255),
    email_lower         VARCHAR(255) GENERATED ALWAYS AS (lower(email)) STORED,
    phone_enc           BYTEA,                            -- pgcrypto 암호화 저장
    phone_normalized    VARCHAR(32),                      -- 정규화 평문(검색용, 마지막 4자리만 활용 정책 권고)
    status              VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
                            CHECK (status IN ('ACTIVE','SUSPENDED','EXPIRED','WITHDRAWN')),
    join_date           DATE         NOT NULL DEFAULT CURRENT_DATE,
    expiry_date         DATE,
    member_type_code    VARCHAR(32)  NOT NULL DEFAULT 'GENERAL',
    iam_user_id         VARCHAR(64),                      -- IAM 연동 user_id (iam_user_link)
    extra               JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by          BIGINT,
    deleted_at          TIMESTAMPTZ,
    version             INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_mbr_member_public_id UNIQUE (public_id)
);

COMMENT ON TABLE  mbr_member                  IS '회원 마스터 (테넌트 격리, PII 컬럼 암호화)';
COMMENT ON COLUMN mbr_member.phone_enc        IS 'pgcrypto AES-256 암호화 전화번호';
COMMENT ON COLUMN mbr_member.phone_normalized IS '검색용 정규화(숫자만). 운영에서는 마지막 4자리만 평문 저장 권고';
COMMENT ON COLUMN mbr_member.member_type_code IS 'cd_code 의 MEMBER_TYPE 그룹 코드';

-- 테넌트 내 회원번호 유일성
CREATE UNIQUE INDEX uk_mbr_member_tenant_member_no
    ON mbr_member (tenant_id, member_no)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_mbr_member_tenant         ON mbr_member (tenant_id);
CREATE INDEX ix_mbr_member_tenant_status  ON mbr_member (tenant_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX ix_mbr_member_tenant_library ON mbr_member (tenant_id, library_id);
CREATE INDEX ix_mbr_member_iam_user       ON mbr_member (iam_user_id) WHERE iam_user_id IS NOT NULL;

-- 부분일치 검색 (이름/이메일/전화)
CREATE INDEX gx_mbr_member_name_trgm   ON mbr_member USING gin (name_normalized gin_trgm_ops);
CREATE INDEX gx_mbr_member_email_trgm  ON mbr_member USING gin (email_lower    gin_trgm_ops);
CREATE INDEX gx_mbr_member_phone_trgm  ON mbr_member USING gin (phone_normalized gin_trgm_ops);

CREATE TRIGGER trg_mbr_member_bu
    BEFORE UPDATE ON mbr_member
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 2. mbr_member_address — 회원 주소 (다건)
--    주소 본문은 암호화. 우편번호는 검색용 평문.
-- =====================================================================
CREATE TABLE mbr_member_address (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    member_id   BIGINT       NOT NULL REFERENCES mbr_member(id) ON DELETE CASCADE,
    type        VARCHAR(16)  NOT NULL DEFAULT 'HOME'
                    CHECK (type IN ('HOME','WORK','SHIPPING','OTHER')),
    zipcode     VARCHAR(10),
    addr1_enc   BYTEA,
    addr2_enc   BYTEA,
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    deleted_at  TIMESTAMPTZ,
    version     INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE mbr_member_address IS '회원 주소 (본문 컬럼 pgcrypto 암호화)';

CREATE INDEX ix_mbr_member_address_tenant ON mbr_member_address (tenant_id);
CREATE INDEX ix_mbr_member_address_member ON mbr_member_address (member_id);
CREATE UNIQUE INDEX uk_mbr_member_address_default
    ON mbr_member_address (member_id)
    WHERE is_default = TRUE AND deleted_at IS NULL;

CREATE TRIGGER trg_mbr_member_address_bu
    BEFORE UPDATE ON mbr_member_address
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 3. mbr_member_card — 회원증/RFID
-- =====================================================================
CREATE TABLE mbr_member_card (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    member_id   BIGINT       NOT NULL REFERENCES mbr_member(id) ON DELETE CASCADE,
    card_no     VARCHAR(64)  NOT NULL,
    barcode     VARCHAR(64),
    rfid_uid    VARCHAR(64),
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('ACTIVE','LOST','REISSUED','EXPIRED','REVOKED')),
    issued_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expired_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    deleted_at  TIMESTAMPTZ,
    version     INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE mbr_member_card IS '회원증 (테넌트 내 card_no/barcode/rfid_uid 유일)';

CREATE UNIQUE INDEX uk_mbr_member_card_tenant_no
    ON mbr_member_card (tenant_id, card_no) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_mbr_member_card_tenant_barcode
    ON mbr_member_card (tenant_id, barcode) WHERE barcode IS NOT NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX uk_mbr_member_card_tenant_rfid
    ON mbr_member_card (tenant_id, rfid_uid) WHERE rfid_uid IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX ix_mbr_member_card_member ON mbr_member_card (member_id);
CREATE INDEX ix_mbr_member_card_tenant_status ON mbr_member_card (tenant_id, status)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_mbr_member_card_bu
    BEFORE UPDATE ON mbr_member_card
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 4. mbr_member_consent — 동의 이력
-- =====================================================================
CREATE TABLE mbr_member_consent (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    member_id   BIGINT       NOT NULL REFERENCES mbr_member(id) ON DELETE CASCADE,
    kind        VARCHAR(32)  NOT NULL
                    CHECK (kind IN ('MARKETING','PRIVACY','THIRD_PARTY','LOCATION','PUSH','EMAIL','SMS')),
    agreed      BOOLEAN      NOT NULL,
    agreed_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    revoked_at  TIMESTAMPTZ,
    consent_version VARCHAR(16) NOT NULL DEFAULT 'v1',
    source      VARCHAR(32),                    -- WEB/MOBILE/KIOSK/OFFLINE
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    deleted_at  TIMESTAMPTZ,
    version     INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE mbr_member_consent IS '회원 동의 이력 (append-only 권장, 철회는 revoked_at 사용)';

CREATE INDEX ix_mbr_member_consent_tenant ON mbr_member_consent (tenant_id);
CREATE INDEX ix_mbr_member_consent_member ON mbr_member_consent (member_id, kind, agreed_at DESC);

CREATE TRIGGER trg_mbr_member_consent_bu
    BEFORE UPDATE ON mbr_member_consent
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 5. mbr_member_credential — 자체 인증 보조(비번/PIN)
--    Keycloak 미연동 회원(키오스크 PIN 등) 한정. 비번은 BCrypt.
-- =====================================================================
CREATE TABLE mbr_member_credential (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    member_id   BIGINT       NOT NULL REFERENCES mbr_member(id) ON DELETE CASCADE,
    kind        VARCHAR(16)  NOT NULL
                    CHECK (kind IN ('PASSWORD','PIN','OTP_SEED')),
    hash        VARCHAR(255) NOT NULL,
    algo        VARCHAR(32)  NOT NULL DEFAULT 'BCRYPT',
    salt        VARCHAR(128),
    failed_count INTEGER     NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    deleted_at  TIMESTAMPTZ,
    version     INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_mbr_member_credential_kind UNIQUE (member_id, kind)
);

COMMENT ON TABLE mbr_member_credential IS '자체 인증용 보조 자격증명 (Keycloak 미연동 케이스)';

CREATE INDEX ix_mbr_member_credential_tenant ON mbr_member_credential (tenant_id);

CREATE TRIGGER trg_mbr_member_credential_bu
    BEFORE UPDATE ON mbr_member_credential
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 6. mbr_member_role — 회원 역할(권한) 부여
-- =====================================================================
CREATE TABLE mbr_member_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    member_id   BIGINT       NOT NULL REFERENCES mbr_member(id) ON DELETE CASCADE,
    role_code   VARCHAR(64)  NOT NULL,
    granted_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    granted_by  BIGINT,
    revoked_at  TIMESTAMPTZ,
    revoked_by  BIGINT,
    reason      TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    deleted_at  TIMESTAMPTZ,
    version     INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE mbr_member_role IS '회원 역할 부여 이력. 활성 역할은 revoked_at IS NULL.';

CREATE UNIQUE INDEX uk_mbr_member_role_active
    ON mbr_member_role (member_id, role_code)
    WHERE revoked_at IS NULL AND deleted_at IS NULL;
CREATE INDEX ix_mbr_member_role_tenant ON mbr_member_role (tenant_id);

CREATE TRIGGER trg_mbr_member_role_bu
    BEFORE UPDATE ON mbr_member_role
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 7. mbr_outbox — 도메인 이벤트 Outbox
-- =====================================================================
CREATE TABLE mbr_outbox (
    id              BIGSERIAL PRIMARY KEY,
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(128) NOT NULL,
    payload         JSONB        NOT NULL,
    tenant_id       BIGINT,
    occurred_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed_at    TIMESTAMPTZ,
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING'
                       CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED')),
    last_error      TEXT,
    trace_id        VARCHAR(64)
);

COMMENT ON TABLE mbr_outbox IS '회원 도메인 이벤트 Outbox (MemberCreated/StatusChanged 등)';

CREATE INDEX ix_mbr_outbox_status_occurred
    ON mbr_outbox (status, occurred_at)
    WHERE status IN ('PENDING','PROCESSING');
CREATE INDEX ix_mbr_outbox_tenant_occurred
    ON mbr_outbox (tenant_id, occurred_at DESC);

-- =====================================================================
-- 8. RLS 정책 — 모든 mbr_* 테이블 tenant_id 격리 (4종 명시)
-- =====================================================================

-- 8.1 mbr_member
ALTER TABLE mbr_member ENABLE ROW LEVEL SECURITY;
ALTER TABLE mbr_member FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_mbr_member_sel ON mbr_member;
CREATE POLICY pol_mbr_member_sel ON mbr_member
    FOR SELECT USING (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_mbr_member_ins ON mbr_member;
CREATE POLICY pol_mbr_member_ins ON mbr_member
    FOR INSERT WITH CHECK (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_mbr_member_upd ON mbr_member;
CREATE POLICY pol_mbr_member_upd ON mbr_member
    FOR UPDATE
    USING (tenant_id = fn_current_tenant_id())
    WITH CHECK (tenant_id = fn_current_tenant_id());

DROP POLICY IF EXISTS pol_mbr_member_del ON mbr_member;
CREATE POLICY pol_mbr_member_del ON mbr_member
    FOR DELETE USING (tenant_id = fn_current_tenant_id());

-- 8.2 동일 패턴 — 매크로 함수로 반복
DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN SELECT unnest(ARRAY[
        'mbr_member_address',
        'mbr_member_card',
        'mbr_member_consent',
        'mbr_member_credential',
        'mbr_member_role'
    ])
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;',  t);

        EXECUTE format('DROP POLICY IF EXISTS pol_%s_sel ON %I;', t, t);
        EXECUTE format(
            'CREATE POLICY pol_%s_sel ON %I FOR SELECT USING (tenant_id = fn_current_tenant_id());',
            t, t);

        EXECUTE format('DROP POLICY IF EXISTS pol_%s_ins ON %I;', t, t);
        EXECUTE format(
            'CREATE POLICY pol_%s_ins ON %I FOR INSERT WITH CHECK (tenant_id = fn_current_tenant_id());',
            t, t);

        EXECUTE format('DROP POLICY IF EXISTS pol_%s_upd ON %I;', t, t);
        EXECUTE format(
            'CREATE POLICY pol_%s_upd ON %I FOR UPDATE USING (tenant_id = fn_current_tenant_id()) WITH CHECK (tenant_id = fn_current_tenant_id());',
            t, t);

        EXECUTE format('DROP POLICY IF EXISTS pol_%s_del ON %I;', t, t);
        EXECUTE format(
            'CREATE POLICY pol_%s_del ON %I FOR DELETE USING (tenant_id = fn_current_tenant_id());',
            t, t);
    END LOOP;
END $$;

-- 8.3 mbr_outbox — tenant_id 격리(NULL 은 SYS 한정)
ALTER TABLE mbr_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE mbr_outbox FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_mbr_outbox_sel ON mbr_outbox;
CREATE POLICY pol_mbr_outbox_sel ON mbr_outbox
    FOR SELECT
    USING (
        tenant_id = fn_current_tenant_id()
        OR tenant_id IS NULL
    );

DROP POLICY IF EXISTS pol_mbr_outbox_ins ON mbr_outbox;
CREATE POLICY pol_mbr_outbox_ins ON mbr_outbox
    FOR INSERT WITH CHECK (
        tenant_id = fn_current_tenant_id()
        OR tenant_id IS NULL
    );

DROP POLICY IF EXISTS pol_mbr_outbox_upd ON mbr_outbox;
CREATE POLICY pol_mbr_outbox_upd ON mbr_outbox
    FOR UPDATE
    USING (tenant_id = fn_current_tenant_id() OR tenant_id IS NULL)
    WITH CHECK (tenant_id = fn_current_tenant_id() OR tenant_id IS NULL);

DROP POLICY IF EXISTS pol_mbr_outbox_del ON mbr_outbox;
CREATE POLICY pol_mbr_outbox_del ON mbr_outbox
    FOR DELETE USING (tenant_id = fn_current_tenant_id() OR tenant_id IS NULL);

-- =====================================================================
-- 9. 옵션: phone_normalized 자동 계산 트리거
--    phone_enc 변경 시 호출자가 평문을 별도로 제공해야 정규화 가능하므로
--    DB 단에서는 입력값 그대로 받는다. 운영에서는 BackendSenior 의
--    common-data/crypto 모듈에서 set 한다.
-- =====================================================================

-- 끝.
