-- =====================================================================
-- Tulip+ IAM Service — Phase 1-B Federation 어댑터 스키마
-- ---------------------------------------------------------------------
-- 작성: BackendDev (1-B.9)
-- 참고:
--   docs/04_dev_lead/05_security_and_auth.md  §5.3 SSO·LDAP 연동
--   docs/10_dba/01_data_modeling_principles.md §5(명명), §6(공통컬럼)
--
-- 본 마이그레이션은 외부 IdP(SAML / OIDC / LDAP) 의 등록 정보와
-- 외부 사용자 ↔ 내부 사용자 매핑을 위한 골격 테이블을 생성한다.
-- Phase 3 의 실제 IdP 연동 시 본 테이블에 운영 데이터가 적재되며,
-- Phase 1-B 시점에는 비어 있는 상태로 배포된다.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. tlp_aut_federation_provider — 테넌트별 IdP 등록
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tlp_aut_federation_provider (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,                  -- 테넌트 식별자 (FK: tlp_cmn_tenant.id)
    provider_id     VARCHAR(64)  NOT NULL,                  -- IdP 식별자 (테넌트 내 UNIQUE)
    type            VARCHAR(16)  NOT NULL,                  -- 프로토콜: SAML / OIDC / LDAP
    display_name    VARCHAR(255) NOT NULL,                  -- 사용자 노출 표시명
    config_json     JSONB,                                  -- 프로토콜별 설정(엔드포인트, 인증서, 매핑규칙 등)
    enabled         BOOLEAN      NOT NULL DEFAULT FALSE,    -- 활성화 여부 (Phase 3 운영 활성화)
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    deleted_at      TIMESTAMPTZ,
    version         INT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_tlp_aut_federation_provider UNIQUE (tenant_id, provider_id),
    CONSTRAINT ck_tlp_aut_federation_provider_type
        CHECK (type IN ('SAML', 'OIDC', 'LDAP'))
);

COMMENT ON TABLE  tlp_aut_federation_provider           IS '외부 SSO(SAML/OIDC/LDAP) IdP 등록 정보';
COMMENT ON COLUMN tlp_aut_federation_provider.tenant_id     IS '테넌트 식별자 (멀티테넌시 격리)';
COMMENT ON COLUMN tlp_aut_federation_provider.provider_id   IS 'IdP 식별자 (테넌트 내 UNIQUE, 콜백 경로의 path 변수로 사용)';
COMMENT ON COLUMN tlp_aut_federation_provider.type          IS '프로토콜 타입: SAML / OIDC / LDAP';
COMMENT ON COLUMN tlp_aut_federation_provider.display_name  IS '로그인 화면 노출 표시명 (예: ○○대학교 통합인증)';
COMMENT ON COLUMN tlp_aut_federation_provider.config_json   IS '프로토콜별 설정(엔드포인트·인증서·속성매핑 등). 민감 정보는 별도 KMS 키로 봉인';
COMMENT ON COLUMN tlp_aut_federation_provider.enabled       IS '활성화 여부 (false 시 라우팅에서 제외)';

CREATE INDEX IF NOT EXISTS ix_tlp_aut_federation_provider_tenant
    ON tlp_aut_federation_provider(tenant_id);
CREATE INDEX IF NOT EXISTS ix_tlp_aut_federation_provider_provider_id
    ON tlp_aut_federation_provider(provider_id);

-- updated_at / version 자동 갱신 트리거 (V1 에서 정의된 함수 재사용)
CREATE TRIGGER trg_tlp_aut_federation_provider_bu
    BEFORE UPDATE ON tlp_aut_federation_provider
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();


-- ---------------------------------------------------------------------
-- 2. tlp_aut_federation_link — 외부 사용자 ↔ 내부 사용자 매핑
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tlp_aut_federation_link (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,                  -- 내부 사용자 ID
    provider_id     VARCHAR(64)  NOT NULL,                  -- IdP 식별자
    external_id     VARCHAR(255) NOT NULL,                  -- IdP 가 발급한 사용자 식별자 (subject/nameid 등)
    attributes_json JSONB,                                  -- 최초 로그인 시 수신한 속성 스냅샷 (감사·디버깅용)
    linked_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),    -- 매핑 생성 시각
    last_login_at   TIMESTAMPTZ,                            -- 최근 로그인 시각 (Phase 3 갱신)
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    deleted_at      TIMESTAMPTZ,
    version         INT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_tlp_aut_federation_link UNIQUE (provider_id, external_id)
);

COMMENT ON TABLE  tlp_aut_federation_link             IS '외부 IdP 사용자(external_id) ↔ 내부 user_id 매핑 (CMN-016)';
COMMENT ON COLUMN tlp_aut_federation_link.user_id         IS '내부 사용자 ID (FK: iam user 테이블)';
COMMENT ON COLUMN tlp_aut_federation_link.provider_id     IS 'IdP 식별자 (tlp_aut_federation_provider.provider_id 참조)';
COMMENT ON COLUMN tlp_aut_federation_link.external_id     IS 'IdP 가 발급한 사용자 고유 식별자 (subject / nameid)';
COMMENT ON COLUMN tlp_aut_federation_link.attributes_json IS '최초 매핑 시점 IdP 속성 스냅샷 (PII 마스킹 적용 후 저장)';
COMMENT ON COLUMN tlp_aut_federation_link.linked_at       IS '매핑 생성 시각';
COMMENT ON COLUMN tlp_aut_federation_link.last_login_at   IS '본 IdP 를 통한 최근 로그인 시각';

CREATE INDEX IF NOT EXISTS ix_tlp_aut_federation_link_user
    ON tlp_aut_federation_link(user_id);
CREATE INDEX IF NOT EXISTS ix_tlp_aut_federation_link_provider_id
    ON tlp_aut_federation_link(provider_id);

CREATE TRIGGER trg_tlp_aut_federation_link_bu
    BEFORE UPDATE ON tlp_aut_federation_link
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
