-- =====================================================================
-- Tulip+ — Phase 1-A 베이스 마이그레이션 (공통 스키마 최소 골격)
-- ---------------------------------------------------------------------
-- 참고:
--   10_dba/01_data_modeling_principles.md §2(RLS), §5(명명), §6(공통컬럼),
--   05_security_and_auth.md §7 (감사로그)
-- 본 파일은 DBA 의 03_core_table_ddl.md 최종 산출물과 정합한다.
-- 운영 적용은 Flyway 가 담당하며, V1 이후의 V2~ 는 별도 PR 로 추가한다.
-- =====================================================================

-- ---------- PostgreSQL 확장 (이미 initdb 에서 적용되었을 수 있음) ----------
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------- 공통: updated_at / version 자동 트리거 ----------
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := now();
  NEW.version := COALESCE(OLD.version, 0) + 1;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- 1. tlp_cmn_tenant — 테넌트 마스터
-- =====================================================================
CREATE TABLE IF NOT EXISTS tlp_cmn_tenant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code     VARCHAR(64)  NOT NULL,
    tenant_name     VARCHAR(255) NOT NULL,
    tenant_type     VARCHAR(32)  NOT NULL,         -- PUBLIC / UNIVERSITY / SCHOOL / SPECIAL
    subscription_plan VARCHAR(32) NOT NULL DEFAULT 'STANDARD',
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE/SUSPENDED/CLOSED
    contact_email   VARCHAR(255),
    contact_phone   VARCHAR(32),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    deleted_at      TIMESTAMPTZ,
    version         INT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_tlp_cmn_tenant_code UNIQUE (tenant_code)
);

CREATE TRIGGER trg_tlp_cmn_tenant_bu
    BEFORE UPDATE ON tlp_cmn_tenant
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 2. tlp_cmn_library — 관(분관) 마스터
-- =====================================================================
CREATE TABLE IF NOT EXISTS tlp_cmn_library (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tlp_cmn_tenant(id),
    library_code    VARCHAR(64)  NOT NULL,
    library_name    VARCHAR(255) NOT NULL,
    is_main         BOOLEAN      NOT NULL DEFAULT FALSE,
    address         VARCHAR(255),
    phone           VARCHAR(32),
    open_hour       VARCHAR(255),                 -- JSON-like 요약 (상세는 별도 테이블)
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    deleted_at      TIMESTAMPTZ,
    version         INT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_tlp_cmn_library_tenant_code UNIQUE (tenant_id, library_code)
);

CREATE INDEX ix_tlp_cmn_library_tenant ON tlp_cmn_library(tenant_id);

CREATE TRIGGER trg_tlp_cmn_library_bu
    BEFORE UPDATE ON tlp_cmn_library
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 3. tlp_cmn_audit_log — 변경 이력 / 접근 이력 통합 골격
-- =====================================================================
CREATE TABLE IF NOT EXISTS tlp_cmn_audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    service         VARCHAR(64)  NOT NULL,
    log_type        VARCHAR(16)  NOT NULL,         -- CHANGE / ACCESS
    entity_type     VARCHAR(64)  NOT NULL,
    entity_id       VARCHAR(128),
    action          VARCHAR(32)  NOT NULL,         -- CREATE/UPDATE/DELETE/READ/EXPORT
    actor_id        BIGINT,
    actor_role      VARCHAR(32),
    before_value    JSONB,
    after_value     JSONB,
    diff            JSONB,
    reason          TEXT,
    client_ip       INET,
    user_agent      TEXT,
    trace_id        VARCHAR(64),
    occurred_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_tlp_cmn_audit_log_tenant_occurred
    ON tlp_cmn_audit_log(tenant_id, occurred_at DESC);
CREATE INDEX ix_tlp_cmn_audit_log_entity
    ON tlp_cmn_audit_log(entity_type, entity_id);

-- append-only 정책: UPDATE/DELETE 차단
CREATE OR REPLACE FUNCTION fn_audit_block_modify()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION '감사 로그는 append-only 입니다.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tlp_cmn_audit_log_block_mod
    BEFORE UPDATE OR DELETE ON tlp_cmn_audit_log
    FOR EACH ROW EXECUTE FUNCTION fn_audit_block_modify();

-- =====================================================================
-- 4. Row Level Security 예시 정책 (tlp_cmn_library)
-- =====================================================================
ALTER TABLE tlp_cmn_library ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_library_tenant_isolation ON tlp_cmn_library;
CREATE POLICY pol_library_tenant_isolation ON tlp_cmn_library
    USING (
        tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::BIGINT
        OR current_setting('app.current_tenant', true) IS NULL
        OR current_setting('app.current_tenant', true) = ''
    );

-- tenant 테이블은 플랫폼 관리자만 접근 — RLS 비활성, 권한 매트릭스로 통제
-- (DBA 06_security_and_access_control.md 참조)

-- =====================================================================
-- 5. 초기 시드 데이터 (개발 환경 sentinel)
-- =====================================================================
INSERT INTO tlp_cmn_tenant (id, tenant_code, tenant_name, tenant_type, status)
VALUES (0, 'SYSTEM', '시스템 공유', 'SPECIAL', 'ACTIVE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tlp_cmn_library (id, tenant_id, library_code, library_name, is_main, status)
VALUES (0, 0, 'SYSTEM', '시스템 공유 관', TRUE, 'ACTIVE')
ON CONFLICT (id) DO NOTHING;
