-- =====================================================================
-- Tulip+ code-policy-service — V1 초기 스키마 (Sprint 1-C)
-- ---------------------------------------------------------------------
-- 작성자 : DBA Agent
-- 작성일 : 2026-05-11
-- 변경요약: cd_code_group / cd_code / pol_policy / pol_policy_assignment
--           + cd_outbox + RLS(글로벌/테넌트 혼합)
-- 참조   : 10_dba/01_data_modeling_principles.md (§7 코드/마스터)
--          04_dev_lead/07_phase1_sprint_plan.md (§5 Sprint 1-C.3, 1-C.4)
-- 정책   : 글로벌 코드(tenant_id IS NULL) 는 모든 사용자 SELECT, 변경은 SYS_ADMIN
--          테넌트 코드(tenant_id = N) 는 해당 테넌트 사용자만 RW
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

-- ----- 공통 트리거/헬퍼 -----
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    NEW.version   := COALESCE(OLD.version, 0) + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_current_tenant_id()
RETURNS BIGINT AS $$
BEGIN
    RETURN NULLIF(current_setting('app.current_tenant', true), '')::BIGINT;
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE OR REPLACE FUNCTION fn_current_app_role()
RETURNS TEXT AS $$
BEGIN
    RETURN NULLIF(current_setting('app.role', true), '');
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql STABLE;

-- =====================================================================
-- 1. cd_code_group — 코드 그룹
--    tenant_id IS NULL = 글로벌(시스템 표준), NOT NULL = 테넌트 확장.
-- =====================================================================
CREATE TABLE cd_code_group (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT,                                    -- NULL=글로벌
    group_code   VARCHAR(64)  NOT NULL,
    name         VARCHAR(200) NOT NULL,
    description  TEXT,
    system_yn    BOOLEAN      NOT NULL DEFAULT FALSE,        -- 시스템 보호 그룹(삭제 금지)
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by   BIGINT,
    deleted_at   TIMESTAMPTZ,
    version      INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE  cd_code_group           IS '코드 그룹 (글로벌=tenant_id NULL, 테넌트 확장=tenant_id N)';
COMMENT ON COLUMN cd_code_group.system_yn IS '시스템 보호 코드 그룹 여부 (TRUE면 삭제 차단)';

-- 글로벌(tenant_id NULL) 그룹 코드 유일성과 테넌트별 유일성을 각각 보장
CREATE UNIQUE INDEX uk_cd_code_group_global_code
    ON cd_code_group (group_code)
    WHERE tenant_id IS NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX uk_cd_code_group_tenant_code
    ON cd_code_group (tenant_id, group_code)
    WHERE tenant_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX ix_cd_code_group_tenant ON cd_code_group (tenant_id);

CREATE TRIGGER trg_cd_code_group_bu
    BEFORE UPDATE ON cd_code_group
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 2. cd_code — 코드 값 (트리 구조 지원)
-- =====================================================================
CREATE TABLE cd_code (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT,                                    -- 그룹과 동일 정책
    group_id     BIGINT       NOT NULL REFERENCES cd_code_group(id) ON DELETE CASCADE,
    code         VARCHAR(64)  NOT NULL,
    name         VARCHAR(200) NOT NULL,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    parent_id    BIGINT       REFERENCES cd_code(id) ON DELETE SET NULL,
    attrs_json   JSONB        NOT NULL DEFAULT '{}'::jsonb,
    enabled_yn   BOOLEAN      NOT NULL DEFAULT TRUE,
    system_yn    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by   BIGINT,
    deleted_at   TIMESTAMPTZ,
    version      INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE  cd_code           IS '코드 값 (그룹 내 트리 구조 지원, parent_id)';
COMMENT ON COLUMN cd_code.attrs_json IS '코드별 확장 속성 (KDC 분류 추가 정보 등)';

CREATE UNIQUE INDEX uk_cd_code_group_code
    ON cd_code (group_id, code)
    WHERE deleted_at IS NULL;
CREATE INDEX ix_cd_code_tenant   ON cd_code (tenant_id);
CREATE INDEX ix_cd_code_group    ON cd_code (group_id, sort_order);
CREATE INDEX ix_cd_code_parent   ON cd_code (parent_id);
CREATE INDEX gx_cd_code_attrs    ON cd_code USING gin (attrs_json);

CREATE TRIGGER trg_cd_code_bu
    BEFORE UPDATE ON cd_code
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 3. pol_policy — 정책 마스터
--    scope: GLOBAL(전체) / TENANT / LIBRARY
--    config_json: 룰 정의 (Phase 4 에서 본격 사용)
-- =====================================================================
CREATE TABLE pol_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT,                                  -- GLOBAL 정책은 NULL
    policy_code     VARCHAR(64)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    scope           VARCHAR(16)  NOT NULL DEFAULT 'TENANT'
                        CHECK (scope IN ('GLOBAL','TENANT','LIBRARY')),
    config_json     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    effective_from  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    effective_to    TIMESTAMPTZ,
    policy_version  INTEGER      NOT NULL DEFAULT 1,
    enabled_yn      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    deleted_at      TIMESTAMPTZ,
    version         INTEGER      NOT NULL DEFAULT 0
);

COMMENT ON TABLE  pol_policy               IS '정책 마스터 (대출 한도/연체 정책 등). config_json=룰 정의.';
COMMENT ON COLUMN pol_policy.policy_version IS '정책 버전(룰 변경 시 +1)';

CREATE UNIQUE INDEX uk_pol_policy_global_code
    ON pol_policy (policy_code)
    WHERE tenant_id IS NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX uk_pol_policy_tenant_code
    ON pol_policy (tenant_id, policy_code)
    WHERE tenant_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX ix_pol_policy_tenant      ON pol_policy (tenant_id);
CREATE INDEX ix_pol_policy_scope_eff   ON pol_policy (scope, effective_from, effective_to);
CREATE INDEX gx_pol_policy_config      ON pol_policy USING gin (config_json);

CREATE TRIGGER trg_pol_policy_bu
    BEFORE UPDATE ON pol_policy
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 4. pol_policy_assignment — 정책 적용 대상
-- =====================================================================
CREATE TABLE pol_policy_assignment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT,
    policy_id   BIGINT       NOT NULL REFERENCES pol_policy(id) ON DELETE CASCADE,
    target_type VARCHAR(32)  NOT NULL
                    CHECK (target_type IN ('LIBRARY','BRANCH','MEMBER_TYPE','ITEM_TYPE','MEMBER','ITEM')),
    target_id   VARCHAR(64)  NOT NULL,
    priority    INTEGER      NOT NULL DEFAULT 100,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    deleted_at  TIMESTAMPTZ,
    version     INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uk_pol_policy_assignment UNIQUE (policy_id, target_type, target_id)
);

COMMENT ON TABLE pol_policy_assignment IS '정책 적용 매핑 (LIBRARY/MEMBER_TYPE 등 대상 + 우선순위)';

CREATE INDEX ix_pol_policy_assignment_tenant ON pol_policy_assignment (tenant_id);
CREATE INDEX ix_pol_policy_assignment_target ON pol_policy_assignment (target_type, target_id, priority);

CREATE TRIGGER trg_pol_policy_assignment_bu
    BEFORE UPDATE ON pol_policy_assignment
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =====================================================================
-- 5. cd_outbox — 도메인 이벤트 Outbox (CodeReloaded 등)
-- =====================================================================
CREATE TABLE cd_outbox (
    id              BIGSERIAL PRIMARY KEY,
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(128) NOT NULL,
    payload         JSONB        NOT NULL,
    tenant_id       BIGINT,
    occurred_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed_at    TIMESTAMPTZ,
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING'
                       CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED')),
    last_error      TEXT,
    trace_id        VARCHAR(64)
);

CREATE INDEX ix_cd_outbox_status_occurred
    ON cd_outbox (status, occurred_at)
    WHERE status IN ('PENDING','PROCESSING');
CREATE INDEX ix_cd_outbox_tenant_occurred
    ON cd_outbox (tenant_id, occurred_at DESC);

-- =====================================================================
-- 6. RLS — 글로벌/테넌트 혼합 정책
--    SELECT: tenant_id IS NULL (글로벌) OR tenant_id = current_tenant
--    INS/UPD/DEL: 글로벌 행은 SYS_ADMIN 만, 테넌트 행은 해당 테넌트만
-- =====================================================================

-- 6.1 cd_code_group
ALTER TABLE cd_code_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE cd_code_group FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_cd_code_group_sel ON cd_code_group;
CREATE POLICY pol_cd_code_group_sel ON cd_code_group
    FOR SELECT
    USING (
        tenant_id IS NULL
        OR tenant_id = fn_current_tenant_id()
    );

DROP POLICY IF EXISTS pol_cd_code_group_ins ON cd_code_group;
CREATE POLICY pol_cd_code_group_ins ON cd_code_group
    FOR INSERT
    WITH CHECK (
        (tenant_id IS NULL  AND fn_current_app_role() = 'SYS_ADMIN')
        OR (tenant_id IS NOT NULL AND tenant_id = fn_current_tenant_id())
    );

DROP POLICY IF EXISTS pol_cd_code_group_upd ON cd_code_group;
CREATE POLICY pol_cd_code_group_upd ON cd_code_group
    FOR UPDATE
    USING (
        (tenant_id IS NULL  AND fn_current_app_role() = 'SYS_ADMIN')
        OR (tenant_id IS NOT NULL AND tenant_id = fn_current_tenant_id())
    )
    WITH CHECK (
        (tenant_id IS NULL  AND fn_current_app_role() = 'SYS_ADMIN')
        OR (tenant_id IS NOT NULL AND tenant_id = fn_current_tenant_id())
    );

DROP POLICY IF EXISTS pol_cd_code_group_del ON cd_code_group;
CREATE POLICY pol_cd_code_group_del ON cd_code_group
    FOR DELETE
    USING (
        (tenant_id IS NULL  AND fn_current_app_role() = 'SYS_ADMIN')
        OR (tenant_id IS NOT NULL AND tenant_id = fn_current_tenant_id())
    );

-- 6.2 cd_code / pol_policy / pol_policy_assignment — 동일 패턴 적용
DO $$
DECLARE
    t TEXT;
BEGIN
    FOR t IN SELECT unnest(ARRAY[
        'cd_code',
        'pol_policy',
        'pol_policy_assignment'
    ])
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;',  t);

        EXECUTE format('DROP POLICY IF EXISTS pol_%s_sel ON %I;', t, t);
        EXECUTE format($f$
            CREATE POLICY pol_%s_sel ON %I FOR SELECT
            USING (tenant_id IS NULL OR tenant_id = fn_current_tenant_id());
        $f$, t, t);

        EXECUTE format('DROP POLICY IF EXISTS pol_%s_ins ON %I;', t, t);
        EXECUTE format($f$
            CREATE POLICY pol_%s_ins ON %I FOR INSERT
            WITH CHECK (
                (tenant_id IS NULL AND fn_current_app_role() = 'SYS_ADMIN')
                OR (tenant_id IS NOT NULL AND tenant_id = fn_current_tenant_id())
            );
        $f$, t, t);

        EXECUTE format('DROP POLICY IF EXISTS pol_%s_upd ON %I;', t, t);
        EXECUTE format($f$
            CREATE POLICY pol_%s_upd ON %I FOR UPDATE
            USING (
                (tenant_id IS NULL AND fn_current_app_role() = 'SYS_ADMIN')
                OR (tenant_id IS NOT NULL AND tenant_id = fn_current_tenant_id())
            )
            WITH CHECK (
                (tenant_id IS NULL AND fn_current_app_role() = 'SYS_ADMIN')
                OR (tenant_id IS NOT NULL AND tenant_id = fn_current_tenant_id())
            );
        $f$, t, t);

        EXECUTE format('DROP POLICY IF EXISTS pol_%s_del ON %I;', t, t);
        EXECUTE format($f$
            CREATE POLICY pol_%s_del ON %I FOR DELETE
            USING (
                (tenant_id IS NULL AND fn_current_app_role() = 'SYS_ADMIN')
                OR (tenant_id IS NOT NULL AND tenant_id = fn_current_tenant_id())
            );
        $f$, t, t);
    END LOOP;
END $$;

-- 6.3 cd_outbox
ALTER TABLE cd_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE cd_outbox FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_cd_outbox_sel ON cd_outbox;
CREATE POLICY pol_cd_outbox_sel ON cd_outbox
    FOR SELECT
    USING (tenant_id = fn_current_tenant_id() OR tenant_id IS NULL);

DROP POLICY IF EXISTS pol_cd_outbox_ins ON cd_outbox;
CREATE POLICY pol_cd_outbox_ins ON cd_outbox
    FOR INSERT WITH CHECK (tenant_id = fn_current_tenant_id() OR tenant_id IS NULL);

DROP POLICY IF EXISTS pol_cd_outbox_upd ON cd_outbox;
CREATE POLICY pol_cd_outbox_upd ON cd_outbox
    FOR UPDATE
    USING (tenant_id = fn_current_tenant_id() OR tenant_id IS NULL)
    WITH CHECK (tenant_id = fn_current_tenant_id() OR tenant_id IS NULL);

DROP POLICY IF EXISTS pol_cd_outbox_del ON cd_outbox;
CREATE POLICY pol_cd_outbox_del ON cd_outbox
    FOR DELETE USING (tenant_id = fn_current_tenant_id() OR tenant_id IS NULL);

-- =====================================================================
-- 7. 시스템 보호 코드 그룹 삭제 차단 트리거
-- =====================================================================
CREATE OR REPLACE FUNCTION fn_cd_block_system_delete()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.system_yn = TRUE THEN
        RAISE EXCEPTION '시스템 보호 코드 그룹은 삭제할 수 없습니다: %', OLD.group_code;
    END IF;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_cd_code_group_bd_system
    BEFORE DELETE ON cd_code_group
    FOR EACH ROW EXECUTE FUNCTION fn_cd_block_system_delete();

-- 끝.
